<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $products = [
            // ==================== CAUDALIE ====================
            ['id' => 1011, 'category_id' => 1, 'name' => 'Caudalie Resveratrol-Lift Crème Cachemire',         'slug' => 'caudalie-resveratrol-lift-creme-cachemire',       'price' => 285.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/caudalie/caudalie1.png', 'description' => 'Crème redensifiante et fermante à la texture cashmere luxueuse. Enrichie en Résveratrol de vigne et acide hyaluronique, elle raffermit la peau, comble les rides et redonne éclat et jeunesse au visage.'],
            ['id' => 1022, 'category_id' => 1, 'name' => 'Caudalie Resveratrol-Lift Gel Yeux',               'slug' => 'caudalie-resveratrol-lift-gel-yeux',             'price' => 195.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/caudalie/caudalie2.png', 'description' => 'Gel contour des yeux liftant et anti-rides. Réduit visiblement les poches et les cernes, raffermit le regard et atténue les signes de fatigue.'],
            ['id' => 1033, 'category_id' => 1, 'name' => 'Caudalie Resveratrol-Lift Sérum',                  'slug' => 'caudalie-resveratrol-lift-serum',                'price' => 320.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/caudalie/caudalie3.png', 'description' => 'Sérum anti-âge liftant fermeté et lissant. Rides visiblement réduites, peau raffermie et éclat retrouvé. Enrichi en Résveratrol de vigne, Huile d\'olive biologique et Peptides de raisin.'],
            ['id' => 1044, 'category_id' => 1, 'name' => 'Caudalie Resveratrol-Lift Crème Nuit',             'slug' => 'caudalie-resveratrol-lift-creme-nuit',           'price' => 295.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/caudalie/caudalie4.png', 'description' => 'Crème de nuit fermeté et éclat. La peau est retendue, lissée et visiblement plus jeune dès le réveil.'],
            ['id' => 1055, 'category_id' => 1, 'name' => 'CAUDALIE Vinoperfect - Sérum Éclat Anti-Taches',   'slug' => 'caudalie-vinoperfect-serum-eclat-anti-taches',   'price' => 300.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/caudalie/caudalie6.png', 'description' => 'Sérum éclaircissant qui réduit visiblement les taches brunes et unifie le teint. Formulé avec la viniférine, un actif breveté issu de la sève de vigne.'],

            // ==================== VISAGE - GEL NETTOYANT ====================
            ['id' => 1,  'category_id' => 1, 'name' => 'La Roche-Posay Effaclar Gel Moussant Purifiant - 200 ml',     'slug' => 'la-roche-posay-effaclar-gel-moussant-200ml',     'price' => 170.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/visage/gel/gel8.png', 'description' => 'Gel nettoyant pour peaux grasses à tendance acnéique. Purifie, élimine l\'excès de sébum et les impuretés. Contient de l\'Eau thermale apaisante et du Zinc PCA matifiant.'],
            ['id' => 2,  'category_id' => 1, 'name' => 'Bioderma Sensibio Gel Moussant - 200 ml',                     'slug' => 'bioderma-sensibio-gel-moussant-200ml',           'price' => 145.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/visage/gel/gel7.png', 'description' => 'Gel nettoyant moussant pour peaux sensibles. Nettoie et démaquille en douceur, hydrate, calme les irritations.'],
            ['id' => 3,  'category_id' => 1, 'name' => 'CeraVe SA Gel Nettoyant Anti-rugosités - 236 ml',             'slug' => 'cerave-sa-gel-nettoyant-anti-rugosite-236ml',    'price' => 129.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/visage/gel/gel2.png', 'description' => 'Gel nettoyant exfoliant pour peaux sèches et rugueuses. Enrichi en 3 céramides, acide hyaluronique et niacinamide.'],
            ['id' => 4,  'category_id' => 1, 'name' => 'URIAGE HYSEAC Gel nettoyant anti-imperfections',              'slug' => 'uriage-hyseac-gel-nettoyant-anti-imperfections', 'price' => 180.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/visage/gel/gel5.png', 'description' => 'Gel nettoyant purifiant pour peaux à imperfections. Élimine l\'excès de sébum, matifie et nettoie en douceur.'],
            ['id' => 5,  'category_id' => 1, 'name' => 'CeraVe Gel Moussant Hydratant - 473 ml',                      'slug' => 'cerave-gel-moussant-hydratant-473ml',            'price' => 168.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/visage/gel/gel4.png', 'description' => 'CeraVe Gel Moussant Hydratant pour Visage et Corps 473ml.'],
            ['id' => 6,  'category_id' => 1, 'name' => 'Bioderma Sensibio DS+ Gel Moussant - 200 ml',                 'slug' => 'bioderma-sensibio-ds-gel-moussant-200ml',        'price' => 169.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/visage/gel/gel6.png', 'description' => 'Gel nettoyant apaisant pour peaux sensibles sujettes aux rougeurs et aux squames. Sans savon, sans parfum.'],
            ['id' => 7,  'category_id' => 1, 'name' => 'CeraVe Gel Moussant Purifiant - 473 ml',                      'slug' => 'cerave-gel-moussant-purifiant-473ml',            'price' => 149.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/visage/gel/gel1.png', 'description' => 'Gel nettoyant moussant pour peaux normales à grasses. Enrichi en 3 céramides, acide hyaluronique et niacinamide.'],
            ['id' => 8,  'category_id' => 1, 'name' => 'CeraVe Gel Moussant Anti-imperfections - 236 ml',             'slug' => 'cerave-gel-moussant-anti-imperfections-236ml',   'price' => 134.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/visage/gel/gel3.png', 'description' => 'Gel nettoyant purifiant pour peaux à imperfections. Formulé avec 2% d\'acide salicylique, argile blanche et niacinamide.'],
            ['id' => 67, 'category_id' => 1, 'name' => 'Uriage Xémose Huile Lavante Apaisante 500ml',                 'slug' => 'uriage-xemose-huile-lavante-apaisante-500ml',    'price' => 129.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/promo/promoo4.png', 'description' => 'Soin nettoyant doux sans savon qui protège contre le dessèchement cutané et apaise les démangeaisons des peaux très sèches à tendance atopique.'],
            ['id' => 70, 'category_id' => 1, 'name' => 'Derm-phy Gel Surgras Dermatologique Uriage 500ml',            'slug' => 'uriage-derm-phy-gel-surgras-500ml',              'price' => 108.25, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/uriage/uriage1.png', 'description' => 'Nettoyant moussant sans savon qui élimine les impuretés tout en préservant le film hydrolipidique des peaux sensibles et sèches.'],
            ['id' => 71, 'category_id' => 1, 'name' => 'Uriage Hyséac Gel Nettoyant 150ml',                           'slug' => 'uriage-hyseac-gel-nettoyant-150ml',              'price' => 192.25, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/uriage/uriage2.png', 'description' => 'Soin lavant doux sans savon pour peaux grasses à tendance acnéique. Nettoie en profondeur sans dessécher.'],

            // ==================== VISAGE - CRÈME HYDRATANTE ====================
            ['id' => 30, 'category_id' => 1, 'name' => 'Avène Cold Cream Nourrit & Protège 40 ml',                    'slug' => 'avene-cold-cream-40ml',                          'price' => 93.10,  'promo_price' => null, 'stock' => 50, 'image_url' => '/images/visage/creme/creme1.png', 'description' => 'Crème nutritive et protectrice à base de Cold Cream et d\'Eau thermale Avène, pour peaux sensibles sèches à très sèches.'],
            ['id' => 31, 'category_id' => 1, 'name' => 'La Roche-Posay Cicaplast Baume B5+ 40 ml',                    'slug' => 'la-roche-posay-cicaplast-baume-b5-40ml',         'price' => 90.00,  'promo_price' => null, 'stock' => 50, 'image_url' => '/images/visage/creme/creme2.png', 'description' => 'Soin réparateur et apaisant pour les peaux fragiles, irritées ou sèches. Répare, nourrit et apaise les rougeurs.'],
            ['id' => 32, 'category_id' => 1, 'name' => 'VICHY Minéral 89 Sérum fortifiant 50 ml',                     'slug' => 'vichy-mineral-89-serum-50ml',                    'price' => 250.20, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/visage/creme/creme3.png', 'description' => 'Sérum fortifiant et hydratant contenant 89% d\'eau volcanique de Vichy et de l\'acide hyaluronique d\'origine naturelle.'],
            ['id' => 33, 'category_id' => 1, 'name' => 'BIODERMA Hydrabio Gel-crème 40 ml',                           'slug' => 'bioderma-hydrabio-gel-creme-40ml',               'price' => 288.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/visage/creme/creme4.png', 'description' => 'Gel-crème hydratant à texture légère pour peaux sensibles normales à mixtes.'],
            ['id' => 34, 'category_id' => 1, 'name' => 'BYOMA Gel-Crème Hydratant 50 ml',                             'slug' => 'byoma-gel-creme-hydratant-50ml',                 'price' => 68.00,  'promo_price' => null, 'stock' => 50, 'image_url' => '/images/visage/creme/creme5.png', 'description' => 'Gel-crème hydratant enrichi en complexe unique de tri-céramides. Sans huile, non comédogène, sans alcool ni parfum.'],
            ['id' => 35, 'category_id' => 1, 'name' => 'Neutrogena Hydro Boost Aqua-Gel 50 ml',                       'slug' => 'neutrogena-hydro-boost-aqua-gel-50ml',           'price' => 100.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/visage/creme/creme6.png', 'description' => 'Grâce à l\'acide hyaluronique et au Tréhalose Botanique, aide à renforcer la barrière cutanée tout en fixant l\'eau dans les cellules.'],
            ['id' => 36, 'category_id' => 1, 'name' => 'CETAPHIL Crème Hydratante 100g',                              'slug' => 'cetaphil-creme-hydratante-100g',                 'price' => 148.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/visage/creme/creme7.png', 'description' => 'Hydratant riche et non gras pour soulagement immédiat et durable, même pour peau extrêmement sèche. Hydratation intense 24h.'],
            ['id' => 37, 'category_id' => 1, 'name' => 'URIAGE Crème d\'Eau Riche Hydratante 40 ml',                 'slug' => 'uriage-creme-eau-riche-40ml',                    'price' => 164.39, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/visage/creme/creme8.png', 'description' => 'Crème à texture riche et onctueuse qui nourrit les peaux assoiffées en profondeur pour un confort instantané.'],
            ['id' => 38, 'category_id' => 1, 'name' => 'BIODERMA SEBIUM HYDRA 40ml',                                  'slug' => 'bioderma-sebium-hydra-40ml',                     'price' => 130.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/visage/creme/creme9.png', 'description' => 'Soin réhydratant et apaisant pour peaux sèches fragilisées par les traitements anti-acné.'],
            ['id' => 72, 'category_id' => 1, 'name' => 'TOLÉDERM CONTROL Soin Calmant Intensif Uriage',               'slug' => 'uriage-tolederm-control-soin-calmant',           'price' => 151.45, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/uriage/uriage3.png', 'description' => 'Soin apaisant haute tolérance qui calme immédiatement les peaux sensibles, réactives ou intolérantes.'],

            // ==================== VISAGE - SÉRUM ====================
            ['id' => 25, 'category_id' => 1, 'name' => 'La Roche-Posay Pure Vitamine C12 Sérum 30 ml',                'slug' => 'la-roche-posay-vitamine-c12-serum-30ml',         'price' => 480.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/visage/serum/serum1.png', 'description' => 'Sérum anti-âge à 12% de vitamine C pure. Illumine le teint, réduit rides et taches, affine le grain de peau.'],
            ['id' => 26, 'category_id' => 1, 'name' => 'The Ordinary Niacinamide 10% + Zinc 1% 30 ml',                'slug' => 'the-ordinary-niacinamide-10-zinc-1-30ml',        'price' => 159.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/visage/serum/serum2.png', 'description' => 'Sérum universel pour peaux sujettes aux imperfections. Réduit les brillances, affine le grain de peau.'],
            ['id' => 27, 'category_id' => 1, 'name' => 'SKIN1004 Madagascar Centella Asiatica Ampoule 100 ml',        'slug' => 'skin1004-centella-asiatica-ampoule-100ml',       'price' => 250.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/visage/serum/serum3.png', 'description' => 'Sérum apaisant concentré formulé avec 100% d\'extrait pur de centella asiatica de Madagascar.'],
            ['id' => 28, 'category_id' => 1, 'name' => 'La Roche-Posay Effaclar Sérum Ultra Concentré 30 ml',         'slug' => 'la-roche-posay-effaclar-serum-ultra-30ml',       'price' => 348.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/visage/serum/serum4.png', 'description' => 'Sérum anti-imperfections effet peeling quotidien pour peaux grasses à tendance acnéique adulte.'],
            ['id' => 29, 'category_id' => 1, 'name' => 'Uriage Hyséac New Skin Serum 40 ml',                          'slug' => 'uriage-hyseac-new-skin-serum-40ml',              'price' => 270.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/visage/serum/serum5.png', 'description' => 'Sérum concentré pour peaux grasses à tendance acnéique. Exfolie, lisse le grain de peau, réduit imperfections.'],
            ['id' => 68, 'category_id' => 1, 'name' => 'VICHY MINERAL 89 SERUM FORTIFIANT 50 ML',                     'slug' => 'vichy-mineral-89-serum-fortifiant-50ml',         'price' => 210.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/visage/serum/serum6.png', 'description' => 'Sérum Booster quotidien fortifiant et repulpant. Hydratation intense sur dix couches pour repulper, lisser et protéger.'],

            // ==================== VISAGE - ÉCRAN SOLAIRE ====================
            ['id' => 21, 'category_id' => 1, 'name' => 'La Roche-Posay Anthelios Ultra-Fluide FPS 50+ 50 ml',         'slug' => 'la-roche-posay-anthelios-ultra-fluide-50ml',     'price' => 260.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/visage/solaire/solaire1.png', 'description' => 'Écran solaire visage ultra-léger, sans huile, fini invisible. Protection large spectre UVA/UVB.'],
            ['id' => 22, 'category_id' => 1, 'name' => 'Avène Ultra Fluid Invisible SPF50+ 50 ml',                    'slug' => 'avene-ultra-fluid-invisible-spf50-50ml',         'price' => 224.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/visage/solaire/solaire2.png', 'description' => 'Fluide solaire très haute protection pour peaux sensibles. Protège des UVB, UVA et de la lumière bleue.'],
            ['id' => 23, 'category_id' => 1, 'name' => 'SVR SUN SECURE Crème SPF50+ 50 ml',                           'slug' => 'svr-sun-secure-creme-spf50-50ml',                'price' => 215.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/visage/solaire/solaire3.png', 'description' => 'Crème solaire très haute protection pour toute la famille. Formule biodégradable respectueuse de l\'environnement.'],
            ['id' => 24, 'category_id' => 1, 'name' => 'Bioderma Photoderm Aquafluide SPF50+ 40 ml',                  'slug' => 'bioderma-photoderm-aquafluide-spf50-40ml',       'price' => 130.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/visage/solaire/solaire4.png', 'description' => 'Fluide solaire très haute protection à la texture ultra-légère. Hydrate 8h, résiste à l\'eau et à la chaleur.'],
            ['id' => 63, 'category_id' => 1, 'name' => 'Vichy Capital Soleil UV-Clear SPF50+ 40 ml',                  'slug' => 'vichy-capital-soleil-uv-clear-spf50-40ml',       'price' => 210.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/visage/solaire/solaire5.png', 'description' => 'Fluide solaire anti-imperfections pour peaux grasses à acnéique. Effet matifiant 12h, fini invisible.'],
            ['id' => 64, 'category_id' => 1, 'name' => 'ISDIN Fusion Water MAGIC SPF 50 50 ml',                       'slug' => 'isdin-fusion-water-magic-spf50-50ml',            'price' => 300.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/visage/solaire/solaire6.png', 'description' => 'Fluide solaire ultra-léger à absorption immédiate. Protège contre UVB/UVA, lumière bleue, infrarouge et pollution.'],
            ['id' => 65, 'category_id' => 1, 'name' => 'Eucerin Sun Sensitive Protect Crème SPF 50+ 50 ml',           'slug' => 'eucerin-sun-sensitive-protect-spf50-50ml',       'price' => 170.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/visage/solaire/solaire7.png', 'description' => 'Crème solaire très haute protection pour peaux sensibles. Technologie Advanced Spectral.'],

            // ==================== CORPS ====================
            ['id' => 9,  'category_id' => 3, 'name' => 'Crème Mixa Nourrissante Protectrice Céramides 400 ml',        'slug' => 'mixa-creme-nourrissante-ceramides-400ml',        'price' => 109.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/corps/creme/img1.png', 'description' => 'Crème corporelle nourrissante et protectrice, enrichie en céramides, pour peaux sèches ou sensibles.'],
            ['id' => 10, 'category_id' => 3, 'name' => 'Mixa Crème Niacinamide Correction Éclat 400 ml',              'slug' => 'mixa-creme-niacinamide-correction-eclat-400ml',  'price' => 120.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/corps/creme/img2.png', 'description' => 'Crème corporelle à la niacinamide pour corriger les imperfections et unifier le teint.'],
            ['id' => 11, 'category_id' => 3, 'name' => 'Mixa Lait Hydratant Corps 400 ml',                            'slug' => 'mixa-lait-hydratant-corps-400ml',                'price' => 85.00,  'promo_price' => null, 'stock' => 50, 'image_url' => '/images/corps/creme/img3.png', 'description' => 'Lait hydratant pour le corps. Nourrit et adoucit la peau.'],
            ['id' => 12, 'category_id' => 3, 'name' => 'Body Lotion Nivea Nourishing Cocoa 400ml',                    'slug' => 'nivea-nourishing-cocoa-body-lotion-400ml',       'price' => 75.00,  'promo_price' => null, 'stock' => 50, 'image_url' => '/images/corps/creme/img4.png', 'description' => 'Lotion pour le corps hydratante au beurre de cacao.'],
            ['id' => 13, 'category_id' => 3, 'name' => 'Body Lotion Nivea Firming 400 ml',                            'slug' => 'nivea-firming-body-lotion-400ml',                'price' => 85.00,  'promo_price' => null, 'stock' => 50, 'image_url' => '/images/corps/creme/img5.png', 'description' => 'Lotion corporelle raffermissante Nivea, format 400 ml.'],
            ['id' => 73, 'category_id' => 3, 'name' => 'Uriage Xémose Lait Émollient 400ml',                          'slug' => 'uriage-xemose-lait-emollient-400ml',             'price' => 170.25, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/uriage/uriage4.png', 'description' => 'Lait émollient hydratant intensif pour peaux sèches à tendance atopique. Hydrate en profondeur et apaise les irritations.'],
            ['id' => 54, 'category_id' => 3, 'name' => 'Tree Hut Coco Colada Gommage 510g',                           'slug' => 'tree-hut-coco-colada-gommage-510g',              'price' => 276.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/corps/gommage/g1.png', 'description' => 'Gommage corporel exfoliant à base de sucre et de beurre de karité. Élimine les cellules mortes, hydrate et laisse la peau douce.'],
            ['id' => 55, 'category_id' => 3, 'name' => 'MATCHA Green Tea Scrub 283g',                                 'slug' => 'matcha-green-tea-scrub-283g',                    'price' => 290.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/corps/gommage/g2.png', 'description' => 'Exfoliant au thé vert matcha et sel marin. Élimine les cellules mortes, purifie et améliore la microcirculation.'],
            ['id' => 56, 'category_id' => 3, 'name' => 'Tree Hut Sunlit Glow Shea Sugar Scrub 510g',                 'slug' => 'tree-hut-sunlit-glow-shea-sugar-scrub-510g',     'price' => 245.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/corps/gommage/g3.png', 'description' => 'Gommage corporel au sucre et beurre de karité. Exfolie en douceur et laisse la peau douce et hydratée.'],
            ['id' => 57, 'category_id' => 3, 'name' => 'Tree Hut Pineapple Gommage 510g',                            'slug' => 'tree-hut-pineapple-gommage-510g',                'price' => 280.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/corps/gommage/g4.png', 'description' => 'Gommage corporel au sucre et beurre de karité, parfum ananas. Laisse la peau douce, lisse et hydratée.'],
            ['id' => 58, 'category_id' => 3, 'name' => 'Watermelon Shea Sugar Scrub 510g',                           'slug' => 'watermelon-shea-sugar-scrub-510g',               'price' => 270.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/corps/gommage/g5.png', 'description' => 'Gommage corporel au sucre et beurre de karité, parfum pastèque. Exfolie et laisse la peau douce et hydratée.'],

            // ==================== CHEVEUX - SHAMPOOING ====================
            ['id' => 14, 'category_id' => 2, 'name' => 'Elseve Shampoing Huile Extraordinaire Jojoba 250 ml',         'slug' => 'elseve-shampoing-huile-jojoba-250ml',            'price' => 42.00,  'promo_price' => null, 'stock' => 50, 'image_url' => '/images/cheveux/shampooing/cham1.png', 'description' => 'Shampooing nourrissant pour cheveux très secs et épais. Enrichi en huile de jojoba.'],
            ['id' => 15, 'category_id' => 2, 'name' => 'Kérastase Reflection Bain Chromatique Riche 250 ml',          'slug' => 'kerastase-reflection-bain-chromatique-250ml',    'price' => 230.77, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/cheveux/shampooing/cham2.png', 'description' => 'Shampooing protecteur de couleur pour cheveux colorés ou méchés très sensibilisés.'],
            ['id' => 39, 'category_id' => 2, 'name' => 'Garnier Ultra Doux Shampooing Huiles d\'Argan et Camélia 300ml','slug' => 'garnier-ultra-doux-shampooing-argan-camelia-300ml','price' => 35.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/cheveux/shampooing/cham3.png', 'description' => 'Shampooing nourrissant sans silicone, 94% d\'origine naturelle, pour cheveux secs et ternes.'],
            ['id' => 40, 'category_id' => 2, 'name' => 'Herbal Essences Argan Oil of Morocco 400ml',                  'slug' => 'herbal-essences-argan-oil-morocco-400ml',        'price' => 65.00,  'promo_price' => null, 'stock' => 50, 'image_url' => '/images/cheveux/shampooing/cham4.png', 'description' => 'Shampooing réparateur à l\'huile d\'argan du Maroc et à l\'aloe vera, sans parabènes ni colorants.'],
            ['id' => 41, 'category_id' => 2, 'name' => 'Pantene Pro-V Intensive Repair 400ml',                        'slug' => 'pantene-pro-v-intensive-repair-400ml',           'price' => 40.00,  'promo_price' => null, 'stock' => 50, 'image_url' => '/images/cheveux/shampooing/cham5.png', 'description' => 'Shampooing réparateur intensif à la formule enrichie en antioxydants.'],
            ['id' => 42, 'category_id' => 2, 'name' => 'Shampooing Ultra Doux Huile d\'Argan et Cranberry 300ml',     'slug' => 'shampooing-ultra-doux-argan-cranberry-300ml',    'price' => 45.00,  'promo_price' => null, 'stock' => 50, 'image_url' => '/images/cheveux/shampooing/cham6.png', 'description' => 'Shampooing nourrissant pour cheveux colorés ou méchés à l\'huile d\'Argan et Cranberry.'],
            ['id' => 43, 'category_id' => 2, 'name' => 'Olaplex No. 4 Bond Maintenance Shampoo 250ml',                'slug' => 'olaplex-no4-bond-maintenance-shampoo-250ml',     'price' => 399.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/cheveux/shampooing/cham7.png', 'description' => 'Shampooing réparateur à la technologie brevetée Olaplex qui reconstruit les liaisons capillaires.'],
            ['id' => 66, 'category_id' => 2, 'name' => 'Vichy Dercos Shampooing Anti-pelliculaire 200ml',             'slug' => 'vichy-dercos-shampooing-anti-pelliculaire-200ml', 'price' => 132.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/promo/promoo3.png', 'description' => 'Shampooing Dercos pour un cuir chevelu sain et des cheveux forts.'],

            // ==================== CHEVEUX - HUILE ====================
            ['id' => 16, 'category_id' => 2, 'name' => 'Gisou Honey Infused Hair Oil 50ml',                           'slug' => 'gisou-honey-infused-hair-oil-50ml',              'price' => 500.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/cheveux/huile/oil1.png', 'description' => 'Huile capillaire infusée au miel, enrichie à l\'huile d\'argan et à l\'huile de coco.'],
            ['id' => 17, 'category_id' => 2, 'name' => 'Kérastase Elixir Ultime L\'Huile Rose 100ml',                'slug' => 'kerastase-elixir-ultime-huile-rose-100ml',       'price' => 520.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/cheveux/huile/oil2.png', 'description' => 'Huile de soin ultra-légère sans rinçage, enrichie en extrait de thé impérial.'],
            ['id' => 44, 'category_id' => 2, 'name' => 'Mielle Rosemary Mint Scalp & Hair Strengthening Oil 59ml',   'slug' => 'mielle-rosemary-mint-hair-oil-59ml',             'price' => 180.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/cheveux/huile/oil3.png', 'description' => 'Huile capillaire fortifiante infusée à la biotine et plus de 30 huiles essentielles.'],
            ['id' => 45, 'category_id' => 2, 'name' => 'Kérastase Elixir Ultime L\'Huile Originale 100ml',           'slug' => 'kerastase-elixir-ultime-huile-originale-100ml',  'price' => 600.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/cheveux/huile/oil4.png', 'description' => 'Huile de soin sublimatrice multi-usages à base d\'huiles précieuses (Argan, Camélia, Marula).'],
            ['id' => 46, 'category_id' => 2, 'name' => 'Olaplex No. 7 Bonding Oil 30ml',                             'slug' => 'olaplex-no7-bonding-oil-30ml',                   'price' => 350.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/cheveux/huile/oil5.png', 'description' => 'Huile coiffante ultra-concentrée qui booste la brillance de 125% et réduit la casse de 77%.'],
            ['id' => 47, 'category_id' => 2, 'name' => 'OGX Coconut Oil Weightless Hydrating Oil 120ml',             'slug' => 'ogx-coconut-oil-hydrating-oil-120ml',            'price' => 156.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/cheveux/huile/oil6.png', 'description' => 'Huile hydratante ultra-légère à l\'huile de coco et extrait de bambou.'],
            ['id' => 48, 'category_id' => 2, 'name' => 'OGX Renewing+ Argan Oil Extra Penetrating Oil 98ml',         'slug' => 'ogx-argan-oil-extra-penetrating-98ml',           'price' => 160.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/cheveux/huile/oil7.png', 'description' => 'Huile capillaire à pénétration extra forte infusée à l\'huile d\'argan du Maroc.'],

            // ==================== CHEVEUX - MASQUE ====================
            ['id' => 18, 'category_id' => 2, 'name' => 'Garnier Fructis Hair Food Ananas 390ml',                      'slug' => 'garnier-fructis-hair-food-ananas-390ml',         'price' => 95.00,  'promo_price' => null, 'stock' => 50, 'image_url' => '/images/cheveux/masque/mask1.png', 'description' => 'Soin capillaire à l\'ananas, 96% d\'ingrédients d\'origine naturelle, pour cheveux longs et ternes.'],
            ['id' => 19, 'category_id' => 2, 'name' => 'Garnier Ultimate Blends Hair Food Banana 390ml',              'slug' => 'garnier-hair-food-banana-390ml',                 'price' => 93.00,  'promo_price' => null, 'stock' => 50, 'image_url' => '/images/cheveux/masque/mask2.png', 'description' => 'Masque 3-en-1 à la banane pour nourrir et réparer les cheveux secs et abîmés.'],
            ['id' => 49, 'category_id' => 2, 'name' => 'Garnier Ultra Doux Masque Rêve Nourrissant 300ml',            'slug' => 'garnier-ultra-doux-masque-nourrissant-300ml',    'price' => 60.00,  'promo_price' => null, 'stock' => 50, 'image_url' => '/images/cheveux/masque/mask3.png', 'description' => 'Masque express nourrissant 1 minute pour cheveux secs et ternes. 97% d\'ingrédients d\'origine naturelle.'],
            ['id' => 50, 'category_id' => 2, 'name' => 'L\'Oréal Professionnel Absolut Repair Masque 250ml',          'slug' => 'loreal-absolut-repair-masque-250ml',             'price' => 216.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/cheveux/masque/mask4.png', 'description' => 'Masque professionnel restructurant à la protéine de blé et au quinoa doré.'],
            ['id' => 51, 'category_id' => 2, 'name' => 'Olaplex No. 8 Rich Hydration Mask 200ml',                    'slug' => 'olaplex-no8-rich-hydration-mask-200ml',          'price' => 400.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/cheveux/masque/mask5.png', 'description' => 'Masque hydratant riche à la technologie brevetée Olaplex. Hydrate profondément et repulpe la fibre capillaire.'],
            ['id' => 52, 'category_id' => 2, 'name' => 'Gisou Honey Gloss Ceramide Therapy Hair Mask 230ml',          'slug' => 'gisou-honey-gloss-ceramide-hair-mask-230ml',     'price' => 550.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/cheveux/masque/mask6.png', 'description' => 'Masque capillaire enrichi au miel Mirsalehi, aux céramides et à l\'acide hyaluronique.'],
            ['id' => 53, 'category_id' => 2, 'name' => 'L\'Oréal Paris Hyaluron Plump Moisture Wrapping Mask 310ml', 'slug' => 'loreal-hyaluron-plump-moisture-mask-310ml',      'price' => 145.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/cheveux/masque/mask7.png', 'description' => 'Masque à l\'acide hyaluronique pour une hydratation intense pendant 72h.'],
            ['id' => 69, 'category_id' => 2, 'name' => 'Kérastase Gloss Absolu Fondant Insta Glaze 250ml',            'slug' => 'kerastase-gloss-absolu-fondant-insta-glaze-250ml','price' => 175.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/promo/promoo2.png', 'description' => 'Soin démêlant sans rinçage qui offre une brillance miroir instantanée enrichi en acide hyaluronique.'],

            // ==================== COMPLÉMENTS ALIMENTAIRES ====================
            ['id' => 20, 'category_id' => 4, 'name' => 'Nature\'s Way Alive! Hair, Skin & Nails Gummies',            'slug' => 'natures-way-alive-hair-skin-nails-gummies',      'price' => 340.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/complement alimentaire/1.png', 'description' => 'Complément multivitaminé en gummies pour cheveux, peau et ongles avec 100mg de collagène et 2500mcg de biotine.'],
            ['id' => 59, 'category_id' => 4, 'name' => 'Biocyte Collagen Express Gummies',                            'slug' => 'biocyte-collagen-express-gummies',               'price' => 250.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/complement alimentaire/2.png', 'description' => 'Complément anti-âge en gummies sans sucre avec 2,5g de collagène et 80mg de vitamine C par dose.'],
            ['id' => 60, 'category_id' => 4, 'name' => 'Nature\'s Bounty Optimal Solutions Hair, Skin & Nails Gummies','slug' => 'natures-bounty-hair-skin-nails-gummies',        'price' => 300.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/complement alimentaire/3.png', 'description' => 'Complément en gummies pour cheveux, peau et ongles avec 2500mcg de biotine par portion.'],
            ['id' => 61, 'category_id' => 4, 'name' => 'Centrum MultiGummies Women',                                  'slug' => 'centrum-multigummies-women',                     'price' => 175.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/complement alimentaire/4.png', 'description' => 'Complément en gommes spécialement conçu pour les femmes. Contient vitamines A, C, D, E, B6, B12 et biotine.'],
            ['id' => 62, 'category_id' => 4, 'name' => 'Nature Made High Absorption Magnesium Glycinate',             'slug' => 'nature-made-magnesium-glycinate',                'price' => 230.00, 'promo_price' => null, 'stock' => 50, 'image_url' => '/images/complement alimentaire/5.png', 'description' => 'Magnésium hautement absorbable sous forme de glycinate chélaté pour réduire la fatigue et le stress.'],
        ];

        // Ajout des timestamps
        $products = array_map(function ($p) {
            $p['created_at'] = now();
            $p['updated_at'] = now();
            return $p;
        }, $products);

        DB::table('products')->insert($products);
    }
}
